---
title: "EDA and numeric summaries"
author: "ASHLEY ROMO"
date: "2023-10-05"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)

# setting the width and height of the plots
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month"))|>
  select(name, id, everything())
```

## Initial numeric work

```{r}
weather_df |> 
  ggplot(aes(x = prcp)) +
  geom_histogram()
```

here are the big outliers
```{r}
weather_df |> 
  filter(prcp > 1000)
```


```{r}
weather_df |> 
  filter(tmax >= 20, tmax <=30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point()
```

## Grouping

```{r}
# can group by multiple variables
weather_df |> 
  group_by(name, month)
```

## Counting
```{r}
#summarize allows use to summarize data within those groups. For example, to count the number of observations use n_obs = n() which reduces the group df into a new df that has the variables you want im the groups you that you started out with
weather_df |> 
  group_by(name, month) |> 
  summarize(n_obs = n())

weather_df |> 
  group_by(month) |> 
  summarize(n_obs = n())
# this output shows you have 24 months and in the 24 months you see the month in the row 1 a total of 93 times
```


```{r}
#count the number of names and can rename the column
weather_df |> 
  count(name, name = "n_obs")
```


```{r}
#de-tidying data to allow the table to be more readable
weather_df |> 
  count(name, month) |> 
  pivot_wider(
    names_from = name, 
    values_from = n
  )
```


## General summaries

```{r}
# takimg the average of each name
# na.rm has a default of FALSE, but you can set it to TRUE, it will take the averages and remove each of the missing values
weather_df |> 
  group_by(name) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE )
  )

#can also group by more than one variable
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE ),
    median_tmax = median(tmax, na.rm = TRUE), 
    sd_tmax = sd(tmax, na.rm = TRUE)
  )
```


```{r}
# plot that shows the average montly temp in each of the stations
weather_df |> 
  group_by(name, month) |> 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) |> 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```



```{r}
#using pivot wider 
#knitr::kable() it structures the data so it looks like the syntax you need for a r markdown table
#digits = 2 rounds the numbers to 2 decimals

weather_df |> 
  group_by(name, month) |> 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) |> 
  pivot_wider(
    names_from = name, 
    values_from = mean_tmax
  ) |> 
  knitr::kable(digits = 2)
```



