---
title: "Viz part 1"
author: "ASHLEY ROMO"
date: "2023-10-05"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)

# setting the width and height of the plots
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```


Let's make a plot

```{r}
#ggplot(dataframe, aes(x = xvariable, y = y variable)) 
#geom_point() = scatter plot 

ggplot(weather_df, aes(x = tmin, y = tmax)) +
         geom_point()
```

Pipes and stuff
```{r}
weather_df |> 
  filter (name == "CentralPark_NY") |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()


#Save ggplots objects

ggp_nyc_weather = 
  weather_df |> 
  filter (name == "CentralPark_NY") |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggp_nyc_weather

```

## Fancy plots

```{r}
#geom_smooth() makes a smooth 
ggplot(weather_df, aes (x = tmin, y = tmax, color = name)) +
  geom_point() +
  geom_smooth()

# move aes to inside geom_point() so only the points are assigned to color
# inside geom_point, you can use alpha shading. ex: alpha = 0.3 to make the points 70% opaque or 30% solid 
ggplot(weather_df, aes (x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.3)+
  geom_smooth()

# se = FALSE gets rid of SE 
ggplot(weather_df, aes (x = tmin, y = tmax)) +
  geom_smooth(se = FALSE)

```

Plot with facets

```{r}
# "." means put everything on this row and then " ~ name" and then have separate columns according to the name variable or whichever variable you chose

ggplot(weather_df, aes(x=tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth() +
  facet_grid(. ~ name)
```


Let's try a different plot. temps are boring

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth() +
  facet_grid (. ~ name)
```

Try assigning a specific color

```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  ggplot(aes(x = date, y = tmax)) +
  geom_point(color = "blue")

# you should rarely assign colors; let R assign them for you

#if there are 2 data example
# also, you can adjust the size of the dots within geom_point(size = 0.5)
weather_df |> 
  filter(name != "CentralPark_NY") |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = 0.7, size = 0.5)

```


hex plot 

```{r}
# to make the dots easier to read --> use geom_hex() which nakes a density plot (kind of like a heat map)

weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()

```

line plot

```{r}
weather_df |> 
  filter(name == "Molokai_HI") |> 
  ggplot(aes(x  = date, y = tmax)) +
  geom_line()

# you can also use geom_line() and geom_point() together

weather_df |> 
  filter(name == "Molokai_HI") |> 
  ggplot(aes(x  = date, y = tmax)) +
  geom_line(alpha = 0.5) + 
  geom_point(size = 0.5)

# line plots are particularly helpful if you are using a longitudianl dataset (ex: if you observations on the same people across different visits)
```


## univariate plotting

Histogram

```{r}
ggplot(weather_df, aes(x = tmax)) +
  geom_histogram()

# to fil the histogram, you can use "fill = variable". ex: fill = name
# you can also make the bars avoid each other by using "position = dodge" within geom_histogram

ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_histogram(position = "dodge")
```

Let's use a density plot

```{r}
# desnity plot allows you see the data better especially when you use "alpha = #.#" within geom_density()
# you can also change the smoothness by using "adjust = #"
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_density(alpha = 0.3, adjust = 2)
```


Using boxplots

```{r}

ggplot(weather_df, aes(y = tmax, x = name)) +
  geom_boxplot()

```

violin plots?
```{r}
ggplot(weather_df, aes(y = tmax, x = name)) +
  geom_violin()

# violin plots you take the density plot and turn it vertically and then mirror it
```

ridge plot

```{r}
# ridge plots are similar to violin plots but it stackes the densities vertically
ggplot(weather_df, aes(x = tmax, y = name)) +
  geom_density_ridges()
```


## saving and embedding plots

```{r}

ggp_weather =
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggsave("results/gg_weather.pdf", ggp_weather)

```


Changing the width and height of the graphs
```{r, fig.width = 6, fig.height= 0.6}
ggp_weather
```


