---
title: "Viz part 2"
author: "ASHLEY ROMO"
date: "2023-10-05"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)

# setting the width and height of the plots
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

This results in a datefrom with `r nrow(weather_df)`observations on six variables. 
## sample plot from last time

```{r}
# to change labels, use "labs()" function. This changes the x and y axis as well as the name of the legend.

weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp (Degree C",
    y = "Max daily temp",
    color = "Location",
    caption = "Max vs. min dailyt temp in three locations; data from moaa"
  )
```

#Scales

```{r}
# breaks allos you to specific when you want the breaks
# you can also transform the y variable by using "trans = ..."
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp (Degree C",
    y = "Max daily temp",
    color = "Location",
    caption = "Max vs. min dailyt temp in three locations; data from moaa"
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0", "15")
  ) +
  scale_y_continuous(
    position = "right", 
    trans = "sqrt"
  )

# you can also apply limits. example: "limits = c(#, #)"
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp (Degree C",
    y = "Max daily temp",
    color = "Location",
    caption = "Max vs. min dailyt temp in three locations; data from moaa"
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0", "15")
  ) +
  scale_y_continuous(
    position = "right", 
    limits = c(0,30)
  )
```



What about colors?

```{r}

# Using viridis package 

weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp (Degree C",
    y = "Max daily temp",
    color = "Location",
    caption = "Max vs. min dailyt temp in three locations; data from moaa"
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0", "15")
  ) +
  scale_y_continuous(
    position = "right", 
    trans = "sqrt"
  ) + 
  viridis::scale_color_viridis(discrete = TRUE) 
```


## Themes

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Min daily temp (Degree C",
    y = "Max daily temp",
    color = "Location",
    caption = "Max vs. min dailyt temp in three locations; data from rnoaa"
    ) +
  viridis::scale_color_viridis(discrete = TRUE) +
  theme_bw() + # gets rid of background color, it resets the whole plot to look like
  theme_classic() + # gets rid of gridlines
  theme_minimal() + # is the same as theme_classic() but without the bakck x and y axis
  theme(legend.position = "bottom")  #this moves the legend to the bottom of the plot
  
```


## data argument . . . 

```{r}
weather_df |> 
  ggplot(aes(x= date, y = tmax)) +
  geom_point(aes(color = name)) +
  geom_smooth()

nyc_weather_df =
  weather_df |> 
  filter(name == "CentralPark_NY")

hawaii_weather_df =
  weather_df |> 
  filter(name == "Molokai_HI")

ggplot(nyc_weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = hawaii_weather_df)
```

## 'patchwork'

```{r}
weather_df |> 
  ggplot(aes(x=date, y = tmax, color = name)) +
  geom_point() +
  facet_grid(. ~ name) # . means no faceting on the rows, name means faceting on the columns
```


```{r}
ggp_temp_scatter =
  weather_df |> 
  ggplot(aes(x=tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5)

ggp_prcp_density = 
  weather_df |> 
  filter(prcp > 25) |> 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.5) +
  theme(legend.position = "bottom")

ggp_tmax_date = 
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  theme(legend.position = "bottom")

# display panels side by side (load the patchwork package)
ggp_temp_scatter + ggp_prcp_density

# diplaying 3 panels together
(ggp_temp_scatter + ggp_prcp_density) / ggp_tmax_date

```


## data manipulation 

```{r}
# change to the factor structure to the variable of interest

weather_df |> 
  mutate(
    name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))
  ) |> 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()


# using reorder example: the variable "name" according to the "tmax" variable

weather_df |> 
  mutate(
    name = fct_reorder(name, tmax )
  ) |> 
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin()

```


## complicated FAS plot

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  separate(group, into = c("dose", "day_of_tx"), sep = 3)

pups_df = 
  read_csv("data/FAS_pups.csv") |> 
  janitor::clean_names() 

fas_df =
  left_join(pups_df, litters_df, by = "litter_number")

fas_df = fas_df |> 
  select(dose, day_of_tx, starts_with("pd")) |> 
  pivot_longer(
    pd_ears:pd_walk, 
    names_to = "outcome",
    values_to = "pn_day"
  ) |> 
  drop_na() |> 
  mutate(
    outcome = fct_reorder(outcome, pn_day)
    ) |> 
  ggplot(aes(x = dose, y = pn_day)) +
  geom_violin() +
  facet_grid(day_of_tx ~ outcome)


```




